const author = {
	name: 'author',
	title: 'Author',
	type: 'document',
	fieldsets: [{ name: 'social', title: 'Social Links' }],
	fields: [
		{
			name: 'name',
			title: 'Name',
			type: 'string',
		},
		{
			name: 'slug',
			title: 'Slug',
			type: 'slug',
			options: {
				source: 'name',
				maxLength: 96,
			},
		},
		{
			name: 'image',
			title: 'Image',
			type: 'image',
			options: {
				hotspot: true,
			},
		},
		{
			name: 'roles',
			title: 'Role/Occupation',
			description: 'What would you describe yourself as?',
			type: 'array',
			of: [{ type: 'string' }],
			validation: (Rule) => [Rule.unique(), Rule.max(15)],
		},
		{
			name: 'skills',
			title: 'Skills & technologies',
			description: 'What skills do you know? A.K.A languages, software, etc.',
			type: 'array',
			of: [{ type: 'string' }],
			validation: (Rule) => [Rule.unique()],
			options: {
				list: [
					{ value: 'Sass', title: 'Sass' },
					{ value: 'JavaScript', title: 'JavaScript' },
					{ value: 'Csharp', title: 'C#' },
					{ value: 'HTML', title: 'HTML' },
					{ value: 'CSS', title: 'CSS' },
					{ value: 'Unity', title: 'Unity' },
					{ value: 'React', title: 'React' },
					{ value: 'Cpp', title: 'C++' },
					{ value: 'Bootstrap', title: 'Bootstrap' },
					{ value: 'NodeJS', title: 'Node.js' },
					{ value: 'Git', title: 'Git' },
					{ value: 'Python', title: 'Python' },
					{ value: 'PHP', title: 'PHP' },
					{ value: 'Unreal-Engine', title: 'Unreal Engine' },
					{ value: 'Java', title: 'Java' },
					{ value: 'Angular', title: 'Angular' },
					{ value: 'Vue', title: 'Vue' },
					{ value: 'Laravel', title: 'Laravel' },
					{ value: 'Django', title: 'Django' },
					{ value: 'C', title: 'C' },
					{ value: 'DotNet', title: '.Net' },
					{ value: 'Kotlin', title: 'Kotlin' },
					{ value: 'Swift', title: 'Swift' },
					{ value: 'Babel', title: 'Babel' },
					{ value: 'Docker', title: 'Docker' },
					{ value: 'Express', title: 'Express' },
					{ value: 'Flask', title: 'Flask' },
					{ value: 'Gulp', title: 'Gulp' },
					{ value: 'jQuery', title: 'jQuery' },
					{ value: 'Linux', title: 'Linux' },
					{ value: 'MongoDB', title: 'MongoDB' },
					{ value: 'MySQL', title: 'MySQL' },
					{ value: 'Objective-C', title: 'Objective-C' },
					{ value: 'OpenGL', title: 'OpenGL' },
					{ value: 'PostgreSQL', title: 'PostgreSQL' },
					{ value: 'R', title: 'R' },
					{ value: 'Ruby', title: 'Ruby' },
					{ value: 'Rust', title: 'Rust' },
					{ value: 'Scala', title: 'Scala' },
					{ value: 'TypeScript', title: 'TypeScript' },
					{ value: 'WordPress', title: 'WordPress' },
					{ value: 'Amp', title: 'Amp' },
					{ value: 'Android', title: 'Android' },
					{ value: 'AWS', title: 'AWS' },
					{ value: 'Azure', title: 'Azure' },
					{ value: 'Bash', title: 'Bash' },
					{ value: 'Clojure', title: 'Clojure' },
					{ value: 'Crystal', title: 'Crystal' },
					{ value: 'Electron', title: 'Electron' },
					{ value: 'Elixr', title: 'Elixr' },
					{ value: 'Firebase', title: 'Firebase' },
					{ value: 'Go', title: 'Go' },
					{ value: 'GraphQL', title: 'GraphQL' },
					{ value: 'Mongoose', title: 'Mongoose' },
					{ value: 'NPM', title: 'NPM' },
					{ value: 'Perl', title: 'Perl' },
					{ value: 'Redux', title: 'Redux' },
				],
			},
		},
		{
			name: 'bio',
			title: 'Bio',
			type: 'text',
		},
		{
			name: 'cv',
			title: 'CV',
			type: 'file',
			options: {
				accept: ['.pdf', '.docx'],
			},
		},
		{
			name: 'github',
			title: 'GitHub',
			type: 'url',
			fieldset: 'social',
		},
		{
			name: 'linkedin',
			title: 'LinkedIn',
			type: 'url',
			fieldset: 'social',
		},
		{
			name: 'email',
			title: 'Email',
			type: 'url',
			validation: (Rule) =>
				Rule.uri({
					scheme: ['mailto'],
				}),
			fieldset: 'social',
		},
	],
	preview: {
		select: {
			title: 'name',
			media: 'image',
		},
	},
};

export default author;
